pr:
  - <branch>

variables:
  - group: <team-name>-general-params
  - name: imageRepository
    value: <app-name>
  - name: dockerfilePath
    value: '$(Pipeline.Workspace)/github/<path-to-dockerfile>'
  - name: tag
    value: '$(Build.BuildId)'
  - name: image
    value: '$(imageRepository):$(tag)'

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Test
    displayName: Unit and integration testing
    jobs:
      - template: templates/docker-test.yml@cet-iac
        parameters:
          jobName: DockerUnitTest
          displayName: Docker compose unit test
          dockerComposeFilePaths:
            - '$(Pipeline.Workspace)/github/docker-compose-unit-tests.yml'
            - '$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml'
