pr: none
trigger:
  branches:
    include:
      - master

variables:
  - group: studadm-general-params
  - group: studadm-spoke1-ref
  - name: appName
    value: kursinfo-web-ref
  - name: parametersFileName
    value: kursinfo-web.ref.parameters.json
  - name: imageRepository
    value: kursinfo-web
  - name: dockerfilePath
    value: '$(Pipeline.Workspace)/github/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'
  - name: image
    value: '$(imageRepository):$(tag)'
  - name: isApi
    value: false

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and push to ref

    jobs:
      - template: templates/deploy-docker-image.yml@cet-iac
