const webContext = {
  lang: 'en',
  proxyPrefixPath: {
    uri: '/student/kurser/kurs',
  },
  courseCode: 'SF1624',
  useStartSemesterFromQuery: false,
  hasStartPeriodFromQuery: false,
  sellingText: {
    en: '',
    sv: '',
  },
  imageFromAdmin: '',
  memoList: {
    20141: {
      60901: {
        courseCode: 'SF1624',
        courseMemoFileName: 'memo-SF162420141-e40e2b8df4ea.pdf',
        applicationCodes: ['60901'],
        lastChangeDate: 'Thu Nov 30 2023 11:57:31 GMT+0100 (Central European Standard Time)',
        semester: '20141',
        previousFileList: [],
        isPdf: true,
      },
    },
    20192: {
      50061: {
        courseCode: 'SF1624',
        applicationCodes: ['50061'],
        semester: '20192',
        memoEndPoint: 'SF162420192-7',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDEPR1 m.fl.  (Startdatum 2019-08-26, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Wed Dec 23 2020 09:42:00 GMT+0000 (Coordinated Universal Time)',
      },
      50088: {
        courseCode: 'SF1624',
        applicationCodes: ['50088'],
        semester: '20192',
        memoEndPoint: 'SF162420192-8',
        memoCommonLangAbbr: 'sv',
        memoName: 'CMETE1 m.fl.  (Startdatum 2019-10-28, Svenska)',
        isPdf: false,
        version: 0,
        lastChangeDate: 'Thu Jun 18 2020 15:08:25 GMT+0200 (Central European Summer Time)',
      },
      50144: {
        courseCode: 'SF1624',
        applicationCodes: ['50144'],
        semester: '20192',
        memoEndPoint: 'SF162420192-3',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDATE1 m.fl.  (Startdatum 2019-10-28, Svenska)',
        isPdf: false,
        version: 0,
        lastChangeDate: 'Wed Jun 17 2020 15:00:25 GMT+0200 (Central European Summer Time)',
      },
      50210: {
        courseCode: 'SF1624',
        applicationCodes: ['50212', '50210'],
        semester: '20192',
        memoEndPoint: 'SF162420192-2',
        memoCommonLangAbbr: 'sv',
        memoName: 'CMEDT1  (Startdatum 2019-10-28, Svenska), CELTE1 m.fl.  (Startdatum 2019-10-28, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Thu Jul 02 2020 15:46:59 GMT+0200 (Central European Summer Time)',
      },
      50212: {
        courseCode: 'SF1624',
        applicationCodes: ['50212', '50210'],
        semester: '20192',
        memoEndPoint: 'SF162420192-2',
        memoCommonLangAbbr: 'sv',
        memoName: 'CMEDT1  (Startdatum 2019-10-28, Svenska), CELTE1 m.fl.  (Startdatum 2019-10-28, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Thu Jul 02 2020 15:46:59 GMT+0200 (Central European Summer Time)',
      },
      50482: {
        courseCode: 'SF1624',
        applicationCodes: ['50482'],
        semester: '20192',
        memoEndPoint: 'SF162420192-5',
        memoCommonLangAbbr: 'sv',
        memoName: 'CITEH1  (Startdatum 2019-10-28, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Mon Jun 29 2020 15:20:19 GMT+0000 (Coordinated Universal Time)',
      },
      50584: {
        courseCode: 'SF1624',
        applicationCodes: ['50584'],
        semester: '20192',
        memoEndPoint: 'SF162420192-1',
        memoCommonLangAbbr: 'sv',
        memoName: 'CBIOT2 m.fl.  (Startdatum 2019-08-26, Svenska)',
        isPdf: false,
        version: 2,
        lastChangeDate: 'Tue Aug 11 2020 08:41:05 GMT+0000 (Coordinated Universal Time)',
      },
      50758: {
        courseCode: 'SF1624',
        applicationCodes: ['50758'],
        semester: '20192',
        memoEndPoint: 'SF162420192-6',
        memoCommonLangAbbr: 'sv',
        memoName: 'CINTE1  (Startdatum 2019-10-28, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Tue Jun 30 2020 06:53:55 GMT+0000 (Coordinated Universal Time)',
      },
      50902: {
        courseCode: 'SF1624',
        applicationCodes: ['50902'],
        semester: '20192',
        memoEndPoint: 'SF162420192-9',
        memoCommonLangAbbr: '',
        memoName: 'CMATD1 m.fl. (Startdatum 2019-10-28, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Fri Mar 27 2020 12:04:37 GMT+0000 (Coordinated Universal Time)',
      },
    },
    20202: {
      50159: {
        courseCode: 'SF1624',
        applicationCodes: ['50159'],
        semester: '20202',
        memoEndPoint: 'SF162420202-9',
        memoCommonLangAbbr: 'sv',
        memoName: 'CBIOT2 m.fl.  (Startdatum 2020-08-24, Svenska)',
        isPdf: false,
        version: 3,
        lastChangeDate: 'Tue Aug 10 2021 10:58:34 GMT+0000 (Coordinated Universal Time)',
      },
      50308: {
        courseCode: 'SF1624',
        applicationCodes: ['50308'],
        semester: '20202',
        memoEndPoint: 'SF162420202-8',
        memoCommonLangAbbr: 'sv',
        memoName: 'CMATD1 m.fl.  (Startdatum 2020-10-26, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Wed Oct 27 2021 10:23:44 GMT+0000 (Coordinated Universal Time)',
      },
      50312: {
        courseCode: 'SF1624',
        applicationCodes: ['50364', '50312'],
        semester: '20202',
        memoEndPoint: 'SF162420202-5-7',
        memoCommonLangAbbr: 'sv',
        memoName: 'CELTE1 m.fl.  (Startdatum 2020-10-26, Svenska), CMETE1 m.fl.  (Startdatum 2020-10-26, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Wed Jul 01 2020 13:37:34 GMT+0000 (Coordinated Universal Time)',
      },
      50316: {
        courseCode: 'SF1624',
        applicationCodes: ['50316'],
        semester: '20202',
        memoEndPoint: 'SF162420202-6',
        memoCommonLangAbbr: 'sv',
        memoName: 'CITEH1  (Startdatum 2020-10-26, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Wed Oct 27 2021 11:40:41 GMT+0000 (Coordinated Universal Time)',
      },
      50364: {
        courseCode: 'SF1624',
        applicationCodes: ['50364', '50312'],
        semester: '20202',
        memoEndPoint: 'SF162420202-5-7',
        memoCommonLangAbbr: 'sv',
        memoName: 'CELTE1 m.fl.  (Startdatum 2020-10-26, Svenska), CMETE1 m.fl.  (Startdatum 2020-10-26, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Wed Jul 01 2020 13:37:34 GMT+0000 (Coordinated Universal Time)',
      },
      50370: {
        courseCode: 'SF1624',
        applicationCodes: ['50370'],
        semester: '20202',
        memoEndPoint: 'SF162420202-4',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDATE1  (Startdatum 2020-10-26, Svenska)',
        isPdf: false,
        version: 3,
        lastChangeDate: 'Thu Jun 04 2020 08:50:16 GMT+0000 (Coordinated Universal Time)',
      },
      50482: {
        courseCode: 'SF1624',
        applicationCodes: ['50482'],
        semester: '20202',
        memoEndPoint: 'SF162420202-3',
        memoCommonLangAbbr: 'sv',
        memoName: 'CINTE1  (Startdatum 2020-10-26, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Fri Jun 26 2020 06:43:12 GMT+0000 (Coordinated Universal Time)',
      },
      51408: {
        courseCode: 'SF1624',
        applicationCodes: ['51408', '51682'],
        semester: '20202',
        memoEndPoint: 'SF162420202-1-2',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDEPR1 m.fl.  (Startdatum 2020-08-24, Svenska), CMEDT1  (Startdatum 2020-10-26, Svenska)',
        isPdf: false,
        version: 0,
        lastChangeDate: 'Thu Nov 18 2021 12:51:55 GMT+0000 (Coordinated Universal Time)',
      },
      51682: {
        courseCode: 'SF1624',
        applicationCodes: ['51408', '51682'],
        semester: '20202',
        memoEndPoint: 'SF162420202-1-2',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDEPR1 m.fl.  (Startdatum 2020-08-24, Svenska), CMEDT1  (Startdatum 2020-10-26, Svenska)',
        isPdf: false,
        version: 0,
        lastChangeDate: 'Thu Nov 18 2021 12:51:55 GMT+0000 (Coordinated Universal Time)',
      },
    },
    20212: {
      50007: {
        courseCode: 'SF1624',
        applicationCodes: ['50007'],
        semester: '20212',
        memoEndPoint: 'SF162420212-8',
        memoCommonLangAbbr: 'sv',
        memoName: 'CBIOT2 m.fl.  (Startdatum 2021-08-30, Svenska)',
        isPdf: false,
        version: 2,
        lastChangeDate: 'Tue Sep 19 2023 09:51:37 GMT+0200 (Central European Summer Time)',
      },
      50081: {
        courseCode: 'SF1624',
        applicationCodes: ['50136', '50096', '50081'],
        semester: '20212',
        memoEndPoint: 'SF162420212-9',
        memoCommonLangAbbr: 'sv',
        memoName:
          'CDATE1  (Startdatum 2021-11-01, Svenska), CITEH1  (Startdatum 2021-11-01, Svenska), CELTE1 m.fl.  (Startdatum 2021-11-01, Svenska)',
        isPdf: false,
        version: 8,
        lastChangeDate: 'Mon Dec 06 2021 15:53:40 GMT+0000 (Coordinated Universal Time)',
      },
      50096: {
        courseCode: 'SF1624',
        applicationCodes: ['50136', '50096', '50081'],
        semester: '20212',
        memoEndPoint: 'SF162420212-9',
        memoCommonLangAbbr: 'sv',
        memoName:
          'CDATE1  (Startdatum 2021-11-01, Svenska), CITEH1  (Startdatum 2021-11-01, Svenska), CELTE1 m.fl.  (Startdatum 2021-11-01, Svenska)',
        isPdf: false,
        version: 8,
        lastChangeDate: 'Mon Dec 06 2021 15:53:40 GMT+0000 (Coordinated Universal Time)',
      },
      50136: {
        courseCode: 'SF1624',
        applicationCodes: ['50136', '50096', '50081'],
        semester: '20212',
        memoEndPoint: 'SF162420212-9',
        memoCommonLangAbbr: 'sv',
        memoName:
          'CDATE1  (Startdatum 2021-11-01, Svenska), CITEH1  (Startdatum 2021-11-01, Svenska), CELTE1 m.fl.  (Startdatum 2021-11-01, Svenska)',
        isPdf: false,
        version: 8,
        lastChangeDate: 'Mon Dec 06 2021 15:53:40 GMT+0000 (Coordinated Universal Time)',
      },
      50353: {
        courseCode: 'SF1624',
        applicationCodes: ['50353'],
        semester: '20212',
        memoEndPoint: 'SF162420212-1',
        memoCommonLangAbbr: 'sv',
        memoName: 'CMEDT1  (Startdatum 2021-11-01, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Wed Apr 07 2021 10:50:54 GMT+0000 (Coordinated Universal Time)',
      },
      50791: {
        courseCode: 'SF1624',
        applicationCodes: ['50791', '51496'],
        semester: '20212',
        memoEndPoint: 'SF162420212-3',
        memoCommonLangAbbr: 'sv',
        memoName: 'CINTE1  (Startdatum 2021-11-01, Svenska), CMATD1 m.fl.  (Startdatum 2021-11-01, Svenska)',
        isPdf: false,
        version: 2,
        lastChangeDate: 'Fri Oct 13 2023 09:23:49 GMT+0200 (Central European Summer Time)',
      },
      51496: {
        courseCode: 'SF1624',
        applicationCodes: ['50791', '51496'],
        semester: '20212',
        memoEndPoint: 'SF162420212-3',
        memoCommonLangAbbr: 'sv',
        memoName: 'CINTE1  (Startdatum 2021-11-01, Svenska), CMATD1 m.fl.  (Startdatum 2021-11-01, Svenska)',
        isPdf: false,
        version: 2,
        lastChangeDate: 'Fri Oct 13 2023 09:23:49 GMT+0200 (Central European Summer Time)',
      },
      51741: {
        courseCode: 'SF1624',
        applicationCodes: ['51741'],
        semester: '20212',
        memoEndPoint: 'SF162420212-2',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDEPR1 m.fl.  (Startdatum 2021-08-30, Svenska)',
        isPdf: false,
        version: 2,
        lastChangeDate: 'Thu Jan 13 2022 10:22:32 GMT+0000 (Coordinated Universal Time)',
      },
    },
    20222: {
      50123: {
        courseCode: 'SF1624',
        applicationCodes: ['50937', '50123'],
        semester: '20222',
        memoEndPoint: 'SF162420222-5-6',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDATE1  (Startdatum 2022-10-31, Svenska), HT 2022-6 (Startdatum 2022-10-31, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Tue May 31 2022 12:50:46 GMT+0200 (Central European Summer Time)',
      },
      50787: {
        courseCode: 'SF1624',
        courseMemoFileName: 'memo-SF162420222-54465be00cb1.pdf',
        applicationCodes: ['50787'],
        lastChangeDate: 'Thu Jun 08 2023 10:59:38 GMT+0200 (Central European Summer Time)',
        semester: '20222',
        previousFileList: [
          {
            courseMemoFileName: 'memo-SF162420222-54465be00cb1.pdf',
            lastChangeDate: 'Wed Jun 07 2023 17:28:23 GMT+0200 (Central European Summer Time)',
            version: 9,
          },
          {
            courseMemoFileName: 'memo-SF162420222-24f76be2f7e2.pdf',
            lastChangeDate: 'Wed Jun 07 2023 17:24:35 GMT+0200 (Central European Summer Time)',
            version: 8,
          },
          {
            courseMemoFileName: 'memo-SF162420222-a49868529481.pdf',
            lastChangeDate: 'Wed Jun 07 2023 17:17:49 GMT+0200 (Central European Summer Time)',
            version: 7,
          },
          {
            courseMemoFileName: 'memo-SF162420222-44a7c9a3b461.pdf',
            lastChangeDate: 'Wed Jun 07 2023 17:14:11 GMT+0200 (Central European Summer Time)',
            version: 6,
          },
          {
            courseMemoFileName: 'memo-SF162420222-c4d75a1ec5c7.pdf',
            lastChangeDate: 'Wed Jun 07 2023 17:13:12 GMT+0200 (Central European Summer Time)',
            version: 5,
          },
          {
            courseMemoFileName: 'memo-SF162420222-14fd69851707.pdf',
            lastChangeDate: 'Wed Jun 07 2023 15:11:00 GMT+0000 (Coordinated Universal Time)',
            version: 4,
          },
          {
            courseMemoFileName: 'memo-SF162420222-14fd69851707.pdf',
            lastChangeDate: 'Wed Jun 07 2023 15:10:59 GMT+0000 (Coordinated Universal Time)',
            version: 3,
          },
          {
            courseMemoFileName: 'memo-SF162420222-d4c76bafa9e0.pdf',
            lastChangeDate: 'Wed Jun 07 2023 17:03:20 GMT+0200 (Central European Summer Time)',
            version: 2,
          },
          {
            courseMemoFileName: 'memo-SF162420222-c4e94bb15c5b.pdf',
            lastChangeDate: 'Mon Jun 05 2023 12:58:02 GMT+0200 (Central European Summer Time)',
            version: 1,
          },
        ],
        isPdf: true,
      },
      50937: {
        courseCode: 'SF1624',
        applicationCodes: ['50937', '50123'],
        semester: '20222',
        memoEndPoint: 'SF162420222-5-6',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDATE1  (Startdatum 2022-10-31, Svenska), HT 2022-6 (Startdatum 2022-10-31, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Tue May 31 2022 12:50:46 GMT+0200 (Central European Summer Time)',
      },
      50956: {
        courseCode: 'SF1624',
        applicationCodes: ['50956'],
        semester: '20222',
        memoEndPoint: 'SF162420222-4',
        memoCommonLangAbbr: 'sv',
        memoName: 'CBIOT2 m.fl.  (Startdatum 2022-08-29, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Fri Dec 09 2022 09:47:22 GMT+0100 (Central European Standard Time)',
      },
      50975: {
        courseCode: 'SF1624',
        applicationCodes: ['50975'],
        semester: '20222',
        memoEndPoint: 'SF162420222-3',
        memoCommonLangAbbr: 'sv',
        memoName: 'CMATD1 m.fl.  (Startdatum 2022-10-31, Svenska)',
        isPdf: false,
        version: 3,
        lastChangeDate: 'Thu Jun 29 2023 10:20:53 GMT+0200 (Central European Summer Time)',
      },
      51637: {
        courseCode: 'SF1624',
        applicationCodes: ['51637'],
        semester: '20222',
        memoEndPoint: 'SF162420222-2',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDEPR1 m.fl.  (Startdatum 2022-08-29, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Wed Jun 29 2022 09:26:24 GMT+0200 (Central European Summer Time)',
      },
    },
    20231: {},
    20232: {
      50075: {
        courseCode: 'SF1624',
        applicationCodes: ['50075'],
        semester: '20232',
        memoEndPoint: 'SF162420232-50075',
        memoCommonLangAbbr: 'sv',
        memoName: 'CITEH1  (Startdatum 2023-10-30, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Mon Sep 18 2023 11:59:12 GMT+0200 (Central European Summer Time)',
      },
      50124: {
        courseCode: 'SF1624',
        applicationCodes: ['50124'],
        semester: '20232',
        memoEndPoint: 'SF162420232-9',
        memoCommonLangAbbr: 'sv',
        memoName: 'CINTE1  (Startdatum 2023-10-30, Svenska)',
        isPdf: false,
        version: 2,
        lastChangeDate: 'Mon Mar 13 2023 09:48:01 GMT+0100 (Central European Standard Time)',
      },
      50264: {
        courseCode: 'SF1624',
        applicationCodes: ['50264'],
        semester: '20232',
        memoEndPoint: 'SF162420232-6',
        memoCommonLangAbbr: 'sv',
        memoName: 'CBIOT2 m.fl.  (Startdatum 2023-08-28, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Tue Sep 05 2023 12:13:03 GMT+0200 (Central European Summer Time)',
      },
      50619: {
        courseCode: 'SF1624',
        applicationCodes: ['50619'],
        semester: '20232',
        memoEndPoint: 'SF162420232-50619-50818',
        memoCommonLangAbbr: 'sv',
        memoName: 'CMETE1 m.fl.  (Startdatum 2023-10-30, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Thu Dec 07 2023 10:28:31 GMT+0100 (Central European Standard Time)',
      },
      50818: {
        courseCode: 'SF1624',
        applicationCodes: ['50818'],
        semester: '20232',
        memoEndPoint: 'SF162420232-50818',
        memoCommonLangAbbr: 'sv',
        memoName: 'CELTE1 m.fl.  (Startdatum 2023-10-30, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Fri Dec 08 2023 11:21:42 GMT+0100 (Central European Standard Time)',
      },
      51279: {
        courseCode: 'SF1624',
        applicationCodes: ['51279'],
        semester: '20232',
        memoEndPoint: 'SF162420232-51279',
        memoCommonLangAbbr: 'sv',
        memoName: 'CMEDT1  (Startdatum 2023-10-30, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Thu Jun 22 2023 11:57:00 GMT+0200 (Central European Summer Time)',
      },
      51350: {
        courseCode: 'SF1624',
        applicationCodes: ['51350'],
        semester: '20232',
        memoEndPoint: 'SF162420232-3',
        memoCommonLangAbbr: 'sv',
        memoName: 'CDATE1  (Startdatum 2023-10-30, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Tue May 09 2023 08:54:08 GMT+0200 (Central European Summer Time)',
      },
      51446: {
        courseCode: 'SF1624',
        applicationCodes: ['51754', '51446'],
        semester: '20232',
        memoEndPoint: 'SF162420232-1-2',
        memoCommonLangAbbr: 'sv',
        memoName: 'CINTE1  (Startdatum 2023-10-30, Svenska), CINTE2  (Startdatum 2023-10-30, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Thu Nov 24 2022 09:54:19 GMT+0100 (Central European Standard Time)',
      },
      51754: {
        courseCode: 'SF1624',
        applicationCodes: ['51754', '51446'],
        semester: '20232',
        memoEndPoint: 'SF162420232-1-2',
        memoCommonLangAbbr: 'sv',
        memoName: 'CINTE1  (Startdatum 2023-10-30, Svenska), CINTE2  (Startdatum 2023-10-30, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Thu Nov 24 2022 09:54:19 GMT+0100 (Central European Standard Time)',
      },
    },
    20251: {
      60290: {
        courseCode: 'SF1624',
        applicationCodes: ['60290'],
        semester: '20251',
        memoEndPoint: 'SF162420251-60290',
        memoCommonLangAbbr: 'sv',
        memoName: 'CYPRESS1  (Startdatum 2025-01-14, Svenska)',
        isPdf: false,
        version: 1,
        lastChangeDate: 'Wed Mar 13 2024 11:30:17 GMT+0100 (Central European Standard Time)',
      },
      60340: {
        courseCode: 'SF1624',
        applicationCodes: ['60340'],
        semester: '20251',
        memoEndPoint: 'SF162420251-60340',
        memoCommonLangAbbr: 'sv',
        memoName: 'CYPRESS2  (Startdatum 2025-01-14, Svenska)',
        isPdf: false,
        version: 5,
        lastChangeDate: 'Wed Mar 13 2024 11:34:36 GMT+0100 (Central European Standard Time)',
      },
      60435: {
        courseCode: 'SF1624',
        courseMemoFileName: 'memo-SF162420251-2422bab73d0c.pdf',
        applicationCodes: ['60435'],
        lastChangeDate: 'Wed Mar 13 2024 11:28:13 GMT+0100 (Central European Standard Time)',
        semester: '20251',
        previousFileList: [
          {
            courseMemoFileName: 'memo-SF162420251-f41a98f6e2bb.pdf',
            lastChangeDate: 'Wed Mar 13 2024 11:28:07 GMT+0100 (Central European Standard Time)',
            version: 2,
          },
          {
            courseMemoFileName: 'memo-SF162420251-a495990457f6.pdf',
            lastChangeDate: 'Wed Mar 13 2024 11:28:03 GMT+0100 (Central European Standard Time)',
            version: 1,
          },
        ],
        isPdf: true,
      },
    },
  },
  isCancelled: false,
  isDeactivated: false,
  keyList: {
    teachers: [
      'SF1624.20232.1.teachers',
      'SF1624.20232.2.teachers',
      'SF1624.20232.3.teachers',
      'SF1624.20232.4.teachers',
      'SF1624.20232.5.teachers',
      'SF1624.20232.6.teachers',
      'SF1624.20232.7.teachers',
      'SF1624.20232.8.teachers',
      'SF1624.20232.9.teachers',
      'SF1624.20242.1.teachers',
      'SF1624.20242.2.teachers',
      'SF1624.20242.3.teachers',
      'SF1624.20242.4.teachers',
      'SF1624.20242.5.teachers',
      'SF1624.20242.6.teachers',
      'SF1624.20242.7.teachers',
      'SF1624.20242.8.teachers',
      'SF1624.20242.9.teachers',
      'SF1624.20251.1.teachers',
      'SF1624.20251.2.teachers',
      'SF1624.20251.3.teachers',
      'SF1624.20251.4.teachers',
    ],
    responsibles: [
      'SF1624.20232.1.courseresponsible',
      'SF1624.20232.2.courseresponsible',
      'SF1624.20232.3.courseresponsible',
      'SF1624.20232.4.courseresponsible',
      'SF1624.20232.5.courseresponsible',
      'SF1624.20232.6.courseresponsible',
      'SF1624.20232.7.courseresponsible',
      'SF1624.20232.8.courseresponsible',
      'SF1624.20232.9.courseresponsible',
      'SF1624.20242.1.courseresponsible',
      'SF1624.20242.2.courseresponsible',
      'SF1624.20242.3.courseresponsible',
      'SF1624.20242.4.courseresponsible',
      'SF1624.20242.5.courseresponsible',
      'SF1624.20242.6.courseresponsible',
      'SF1624.20242.7.courseresponsible',
      'SF1624.20242.8.courseresponsible',
      'SF1624.20242.9.courseresponsible',
      'SF1624.20251.1.courseresponsible',
      'SF1624.20251.2.courseresponsible',
      'SF1624.20251.3.courseresponsible',
      'SF1624.20251.4.courseresponsible',
    ],
  },
  activeSemesters: [
    ['2023', '2', '20232', 0],
    ['2024', '2', '20242', 0],
    ['2025', '1', '20251', 0],
  ],
  activeSemestersIndexesWithValidSyllabusesIndexes: [0, 0, 0],
  defaultIndex: 1,
  activeRoundIndex: 0,
  activeSemesterIndex: 0,
  activeSemester: '20242',
  activeSyllabusIndex: 0,
  dropdownsOpen: {
    roundsDropdown: false,
    semesterDropdown: false,
  },
  roundInfoFade: false,
  syllabusInfoFade: false,
  showRoundData: false,
  roundDisabled: false,
  semesterSelectedIndex: 0,
  roundSelectedIndex: 0,
  courseData: {
    syllabusList: [
      {
        course_goals:
          '<p>After the course the student should be able to</p><ul><li>use concepts. theorems and methods to solve and present solutions to problems within the parts of linear algebra described by the course content,</li><li>read and comprehend mathematical text.</li></ul>',
        course_content:
          "<p>Vectors, matrices, linear equations, Gaussian elimination, vector&#160; geometry with dot product and vector product, determinants, vector spaces, linear independence, bases, change of basis, linear transformations, the least-squares method, eigenvalues, eigenvectors, quadratic forms, orthogonality, inner-product space, Gram-Schmidt's method.</p>",
        course_disposition: '<i>No information inserted</i>',
        course_eligibility: '<p>Basic requirements.&#160;</p><p><strong>&#160;</strong></p>',
        course_requirments_for_final_grade:
          '<p>Written exam, possibly with the possibility of continuous examination.</p>',
        course_literature: '<i>No information inserted</i>',
        course_literature_comment:
          '<p>Announced no later than 4 weeks before the start of the course on the course web page.</p>',
        course_valid_from: ['2019', '2'],
        course_valid_to: [],
        course_required_equipment: '<i>No information inserted</i>',
        course_examination:
          "<ul class='ul-no-padding' ><li>TEN1 - \n                        Examination,\n                        7.5  credits,  \n                        grading scale: A, B, C, D, E, FX, F              \n                        </li></ul>",
        course_examination_comments:
          'Based on recommendation from KTH’s coordinator for disabilities, the examiner will decide how to adapt an examination for students with documented disability. <br><br>The examiner may apply another examination format when re-examining individual students.<p>The examiner decides, in consultation with KTHs Coordinator of students with disabilities (Funka), about any customized examination for students with documented, lasting disability.&#160;</p>',
        course_ethical:
          "<ul><li>All members of a group are responsible for the group's work.</li><li>In any assessment, every student shall honestly disclose any help received and sources used.</li><li>In an oral assessment, every student shall be able to present and answer questions about the entire assignment and solution.</li></ul>",
        course_establishment: 'Course syllabus for SF1624 valid from Autumn 2019',
        course_additional_regulations: '',
        course_transitional_reg: '',
        course_decision_to_discontinue: '<i>No information inserted</i>',
      },
      {
        course_goals:
          '<p>After completing the course students should for a passing grade be able to</p><ul><li>use the basic concepts and problem solving methods in linear&#160;algebra and geometry. In particular it means to be able to:<br />- understand, interpret and use the basic concepts: the vector space&#160;Rn, subspaces of Rn, linear dependence and independence, basis,&#160;dimension, linear transformations, matrix, determinant, eigenvalue and&#160;eigenvector.<br />- solve geometric problems in two and three dimensions using for&#160;example vectors, dot product, vector product, triple product and&#160;projection.<br />- use Gauss-Jordan?s method for example to solve linear systems of&#160;equations, calculate inverse matrices, determinants and to resolve&#160;questions about linearly independent.<br />- use matrix and determinant calculus to address issues regarding&#160;linear transformations and linear systems.<br />- use the least-squares method to solve for example problems with&#160;over-determined linear systems of equations.<br />- use different bases for vector spaces to handle vectors and linear&#160;transformations, and to manage changes of bases and linear coordinate&#160;transformations.<br />- compute eigenvalues and eigenvectors and use this for example in&#160;order to diagonalize matrices, to study quadratic forms, conics in the&#160;plane and quadratic surfaces in three space.<br />- use the Euclidean inner product in order to address the questions&#160;<br />about distance, orthogonality and projection, and apply Gram-Schmidt?s&#160;<br />method to calculate orthogonal bases of subspaces.</li><li>set up simple mathematical models where the fundamental concepts&#160;in linear algebra and geometry are used, discuss the relevance of such&#160;<br />models, reasonableness and accuracy, and know how mathematical&#160; software can be used for calculations and visualization.</li><li>read and understand mathematical texts about for example,&#160; vectors, matrices, linear transformations and their applications,&#160;communicate mathematical reasoning and calculations in this area,&#160;orally and in writing in such a way that they are easy to follow.</li></ul><p>For higher grades, the student in addition should be able to:</p><ul><li>manage general vector spaces, such as function spaces or vector&#160;spaces of matrices. </li><li>use other inner products than the Euclidean inner product.</li><li>derive important relations in linear algebra and geometry.</li><li>generalize and adapt the methods to use in somewhat new contexts.</li><li>solve problems that require synthesis of material and ideas from&#160;all over the course.</li><li>describe the theory behind concepts such as eigenvalues and&#160;orthogonality.</li></ul>',
        course_content:
          '<p>Vectors, matrices, linear equations, Gaussian elimination, vector&#160; geometry with dot product and vector product, determinants, vector&#160;spaces, linear independence, bases, change of basis, the least-squares&#160;method, eigenvalues, eigenvectors, quadratic forms, orthogonality,&#160;inner-product space, Gram-Schmidt?s method</p>',
        course_disposition: '<i>No information inserted</i>',
        course_eligibility:
          '<p>Basic and specific requirements for engineering program.<br /><strong>Mandatory for first year, can not be read by other students</strong></p>',
        course_requirments_for_final_grade:
          '<p>Written exam, possibly with the possibility of continuous examination.</p>',
        course_literature: '<i>No information inserted</i>',
        course_literature_comment: '<i>No information inserted</i>',
        course_valid_from: ['2010', '2'],
        course_valid_to: [2019, '1'],
        course_required_equipment: '<i>No information inserted</i>',
        course_examination:
          "<ul class='ul-no-padding' ><li>TEN1 - \n                        Examination,\n                        7.5  credits,  \n                        grading scale: A, B, C, D, E, FX, F              \n                        </li></ul>",
        course_examination_comments:
          'Based on recommendation from KTH’s coordinator for disabilities, the examiner will decide how to adapt an examination for students with documented disability. <br><br>The examiner may apply another examination format when re-examining individual students.',
        course_ethical:
          "<ul><li>All members of a group are responsible for the group's work.</li><li>In any assessment, every student shall honestly disclose any help received and sources used.</li><li>In an oral assessment, every student shall be able to present and answer questions about the entire assignment and solution.</li></ul>",
        course_establishment: 'Course syllabus for SF1624 valid from Autumn 2010',
        course_additional_regulations: '',
        course_transitional_reg: '',
        course_decision_to_discontinue: '<i>No information inserted</i>',
      },
      {
        course_goals: '<i>No information inserted</i>',
        course_content: '<i>No information inserted</i>',
        course_disposition: '<i>No information inserted</i>',
        course_eligibility: '<i>No information inserted</i>',
        course_requirments_for_final_grade: '',
        course_literature: '<i>No information inserted</i>',
        course_literature_comment: '<i>No information inserted</i>',
        course_valid_from: ['2009', '2'],
        course_valid_to: [2010, '1'],
        course_required_equipment: '<i>No information inserted</i>',
        course_examination:
          "<ul class='ul-no-padding' ><li>TEN1 - \n                        Examination,\n                        7.5  credits,  \n                        grading scale: A, B, C, D, E, FX, F              \n                        </li></ul>",
        course_examination_comments:
          'Based on recommendation from KTH’s coordinator for disabilities, the examiner will decide how to adapt an examination for students with documented disability. <br><br>The examiner may apply another examination format when re-examining individual students.',
        course_ethical:
          "<ul><li>All members of a group are responsible for the group's work.</li><li>In any assessment, every student shall honestly disclose any help received and sources used.</li><li>In an oral assessment, every student shall be able to present and answer questions about the entire assignment and solution.</li></ul>",
        course_establishment: 'Course syllabus for SF1624 valid from Autumn 2009',
        course_additional_regulations: '',
        course_transitional_reg: '',
        course_decision_to_discontinue: '<i>No information inserted</i>',
      },
      {
        course_goals: '<i>No information inserted</i>',
        course_content: '<i>No information inserted</i>',
        course_disposition: '<i>No information inserted</i>',
        course_eligibility: '<i>No information inserted</i>',
        course_requirments_for_final_grade: '',
        course_literature: '<i>No information inserted</i>',
        course_literature_comment: '<i>No information inserted</i>',
        course_valid_from: ['2008', '2'],
        course_valid_to: [2009, '1'],
        course_required_equipment: '<i>No information inserted</i>',
        course_examination:
          "<ul class='ul-no-padding' ><li>TEN1 - \n                        Examination,\n                        7.5  credits,  \n                        grading scale: A, B, C, D, E, FX, F              \n                        </li></ul>",
        course_examination_comments:
          'Based on recommendation from KTH’s coordinator for disabilities, the examiner will decide how to adapt an examination for students with documented disability. <br><br>The examiner may apply another examination format when re-examining individual students.',
        course_ethical:
          "<ul><li>All members of a group are responsible for the group's work.</li><li>In any assessment, every student shall honestly disclose any help received and sources used.</li><li>In an oral assessment, every student shall be able to present and answer questions about the entire assignment and solution.</li></ul>",
        course_establishment: 'Course syllabus for SF1624 valid from Autumn 2008',
        course_additional_regulations: '',
        course_transitional_reg: '',
        course_decision_to_discontinue: '<i>No information inserted</i>',
      },
    ],
    courseInfo: {
      course_application_info: '',
      course_code: 'SF1624',
      course_contact_name: '<i>No information inserted</i>',
      course_department: 'SCI/Mathematics',
      course_department_code: 'SF',
      course_department_link: '<a href="/sci/" target="blank">SCI/Mathematics</a>',
      course_education_type_id: 22,
      course_examiners:
        '<p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/sst" alt="Profile picture" width="31" height="31">\n      <a href="/profile/sst/" property="teach:teacher">\n          Stefan Sundkvist \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/testuge" alt="Profile picture" width="31" height="31">\n      <a href="/profile/testuge/" property="teach:teacher">\n          Test UG Gruppeditor Detectify \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/bichel" alt="Profile picture" width="31" height="31">\n      <a href="/profile/bichel/" property="teach:teacher">\n          Johannes Bichel \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/jeskla" alt="Profile picture" width="31" height="31">\n      <a href="/profile/jeskla/" property="teach:teacher">\n          Jessica Klarström \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/jocke" alt="Profile picture" width="31" height="31">\n      <a href="/profile/jocke/" property="teach:teacher">\n          Joakim Petersson \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/elenara" alt="Profile picture" width="31" height="31">\n      <a href="/profile/elenara/" property="teach:teacher">\n          Elena Rakhimova \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/savela" alt="Profile picture" width="31" height="31">\n      <a href="/profile/savela/" property="teach:teacher">\n          Maria Savela \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/ninavz" alt="Profile picture" width="31" height="31">\n      <a href="/profile/ninavz/" property="teach:teacher">\n          Nina von Zeipel \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/madjidi" alt="Profile picture" width="31" height="31">\n      <a href="/profile/madjidi/" property="teach:teacher">\n          Payam Madjidi \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/tillman" alt="Profile picture" width="31" height="31">\n      <a href="/profile/tillman/" property="teach:teacher">\n          Katarina Tillman \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/sabahat" alt="Profile picture" width="31" height="31">\n      <a href="/profile/sabahat/" property="teach:teacher">\n          Rao Sabahat Ali Khan \n      </a> \n    </p>  <p class = "person">\n      <img class="profile-picture" src="https://www.kth.se/files/thumbnail/testkui" alt="Profile picture" width="31" height="31">\n      <a href="/profile/testkui/" property="teach:teacher">\n          Test Kursinfo admin Detectify \n      </a> \n    </p>  ',
      course_grade_scale: 'A, B, C, D, E, FX, F',
      course_last_exam: [],
      course_level_code: 'BASIC',
      course_literature: '<i>No information inserted</i>',
      course_main_subject: 'Mathematics, Technology',
      course_possibility_to_addition: '<i>No information inserted</i>',
      course_possibility_to_completions: '<i>No information inserted</i>',
      course_prerequisites: '<i>No information inserted</i>',
      course_recruitment_text: '',
      course_required_equipment: '<i>No information inserted</i>',
      course_suggested_addon_studies: '<i>No information inserted</i>',
      course_supplemental_information_url: '<i>No information inserted</i>',
      course_supplemental_information_url_text: '<i>No information inserted</i>',
      course_state: 'ESTABLISHED',
      sellingText: '<p>Text for &quot;Introduktion till kursen (EN)&quot; from Cypress (2024-03-13T09:16:46.486Z)</p>',
      imageFromAdmin: '',
      course_disposition: '<p>Text for &quot;Kursupplägg (EN)&quot; from Cypress (2024-03-13T09:16:46.486Z)</p>',
      course_supplemental_information: '<p>Text for Övrig information (EN) from Cypress (2024-03-13T09:17:20.238Z)</p>',
    },
    roundList: {
      20232: [
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '28 Aug 2023',
          round_end_date: '27 Oct 2023',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CDEPR1 m.fl.',
          round_application_code: '51754',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2023', '2'],
          round_periods: 'P1 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CDEPR/20232/arskurs1">\n          Degree Programme in Design and Product Realisation, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CENMI/20232/arskurs1">\n          Degree Programme in Energy and Environment, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CLGYM/20222/arskurs2#inrTEMI">\n          Master of Science in Engineering and in Education, åk 2, TEMI, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '30 Oct 2023',
          round_end_date: '15 Jan 2024',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CMATD1 m.fl.',
          round_application_code: '51446',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2023', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CSAMH/20232/arskurs1">\n          Degree Programme in Civil Engineering and Urban Management, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CTKEM/20232/arskurs1">\n          Degree Programme in Engineering Chemistry, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CMATD/20232/arskurs1">\n          Degree Programme in Materials Design and Engineering, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CLGYM/20222/arskurs2#inrMAKE">\n          Master of Science in Engineering and in Education, åk 2, MAKE, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CLGYM/20222/arskurs2#inrTEDA">\n          Master of Science in Engineering and in Education, åk 2, TEDA, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '30 Oct 2023',
          round_end_date: '15 Jan 2024',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CDATE1',
          round_application_code: '51350',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2023', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CDATE/20232/arskurs1">\n          Degree Programme in Computer Science and Engineering, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '30 Oct 2023',
          round_end_date: '15 Jan 2024',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CMEDT1',
          round_application_code: '51279',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2023', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CMEDT/20232/arskurs1">\n          Degree Programme in Medical Engineering, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '30 Oct 2023',
          round_end_date: '15 Jan 2024',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CITEH1',
          round_application_code: '50075',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2023', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CITEH/20232/arskurs1">\n          Degree Programme in Industrial Technology and Sustainability, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '28 Aug 2023',
          round_end_date: '27 Oct 2023',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CBIOT2 m.fl.',
          round_application_code: '50264',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2023', '2'],
          round_periods: 'P1 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CBIOT/20222/arskurs2">\n          Degree Programme in Biotechnology, åk 2, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CMAST/20232/arskurs1">\n          Degree Programme in Mechanical Engineering, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '30 Oct 2023',
          round_end_date: '15 Jan 2024',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CELTE1 m.fl.',
          round_application_code: '50818',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2023', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CELTE/20232/arskurs1">\n          Degree Programme in Electrical Engineering, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CINEK/20232/arskurs1">\n          Degree Programme in Industrial Engineering and Management, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '30 Oct 2023',
          round_end_date: '15 Jan 2024',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CMETE1 m.fl.',
          round_application_code: '50619',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2023', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/COPEN/20232/arskurs1">\n          Degree Programme Open Entrance, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CMETE/20232/arskurs1">\n          Degree Programme in Media Technology, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '30 Oct 2023',
          round_end_date: '15 Jan 2024',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Kista',
          round_campus: 'KTH Kista',
          round_short_name: 'CINTE1',
          round_application_code: '50124',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2023', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CINTE/20232/arskurs1">\n          Degree Programme in Information and Communication Technology, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
      ],
      20242: [
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '28 Oct 2024',
          round_end_date: '13 Jan 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CMETE1 m.fl.',
          round_application_code: '50233',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2024', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/COPEN/20242/arskurs1">\n          Degree Programme Open Entrance, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CMETE/20242/arskurs1">\n          Degree Programme in Media Technology, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '28 Oct 2024',
          round_end_date: '13 Jan 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CITEH1',
          round_application_code: '50332',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2024', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme: '<i>No information inserted</i>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '28 Oct 2024',
          round_end_date: '13 Jan 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Kista',
          round_campus: 'KTH Kista',
          round_short_name: 'CINTE1',
          round_application_code: '51098',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2024', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CINTE/20242/arskurs1">\n          Degree Programme in Information and Communication Technology, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '26 Aug 2024',
          round_end_date: '27 Oct 2024',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CBIOT2 m.fl.',
          round_application_code: '50748',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2024', '2'],
          round_periods: 'P1 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CBIOT/20232/arskurs2">\n          Degree Programme in Biotechnology, åk 2, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CITEH/20242/arskurs1">\n          Degree Programme in Industrial Technology and Sustainability, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CMAST/20242/arskurs1">\n          Degree Programme in Mechanical Engineering, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '26 Aug 2024',
          round_end_date: '27 Oct 2024',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CDEPR1 m.fl.',
          round_application_code: '51505',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2024', '2'],
          round_periods: 'P1 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CDEPR/20242/arskurs1">\n          Degree Programme in Design and Product Realisation, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CENMI/20242/arskurs1">\n          Degree Programme in Energy and Environment, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CLGYM/20232/arskurs2#inrTEMI">\n          Master of Science in Engineering and in Education, åk 2, TEMI, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '28 Oct 2024',
          round_end_date: '13 Jan 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CMEDT1',
          round_application_code: '51143',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2024', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CMEDT/20242/arskurs1">\n          Degree Programme in Medical Engineering, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '28 Oct 2024',
          round_end_date: '13 Jan 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CDATE1',
          round_application_code: '50225',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2024', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CDATE/20242/arskurs1">\n          Degree Programme in Computer Science and Engineering, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '28 Oct 2024',
          round_end_date: '13 Jan 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CELTE1 m.fl.',
          round_application_code: '50166',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2024', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CELTE/20242/arskurs1">\n          Degree Programme in Electrical Engineering, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CINEK/20242/arskurs1">\n          Degree Programme in Industrial Engineering and Management, åk 1, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '28 Oct 2024',
          round_end_date: '13 Jan 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CMATD1 m.fl.',
          round_application_code: '50036',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 50,
          round_course_term: ['2024', '2'],
          round_periods: 'P2 (7.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme:
            '<p>\n        <a href="/student/kurser/program/CSAMH/20242/arskurs1">\n          Degree Programme in Civil Engineering and Urban Management, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CTKEM/20242/arskurs1">\n          Degree Programme in Engineering Chemistry, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CMATD/20242/arskurs1">\n          Degree Programme in Materials Design and Engineering, åk 1, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CLGYM/20232/arskurs2#inrMAKE">\n          Master of Science in Engineering and in Education, åk 2, MAKE, Mandatory\n      </a>\n    </p><p>\n        <a href="/student/kurser/program/CLGYM/20232/arskurs2#inrTEDA">\n          Master of Science in Engineering and in Education, åk 2, TEDA, Mandatory\n      </a>\n    </p>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
      ],
      20251: [
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '14 Jan 2025',
          round_end_date: '30 Jun 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CYPRESS1',
          round_application_code: '60290',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 17,
          round_course_term: ['2025', '1'],
          round_periods: 'P3 (2.0 hp), P4 (4.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme: '<i>No information inserted</i>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '14 Jan 2025',
          round_end_date: '30 Jun 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CYPRESS2',
          round_application_code: '60340',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 17,
          round_course_term: ['2025', '1'],
          round_periods: 'P3 (2.0 hp), P4 (4.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme: '<i>No information inserted</i>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '14 Jan 2025',
          round_end_date: '30 Jun 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CYPRESS3',
          round_application_code: '60435',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 17,
          round_course_term: ['2025', '1'],
          round_periods: 'P3 (2.0 hp), P4 (4.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme: '<i>No information inserted</i>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
          round_memoFile: {
            fileName: 'memo-SF162420251-2422bab73d0c.pdf',
            fileDate: '03/13/2024, 11:28:13 AM',
          },
          has_round_published_memo: true,
        },
        {
          round_time_slots: '<i>No information inserted</i>',
          round_start_date: '14 Jan 2025',
          round_end_date: '30 Jun 2025',
          round_target_group: '<i>No information inserted</i>',
          round_tutoring_form: 'NML',
          round_tutoring_time: 'DAG',
          round_tutoring_language: 'Swedish',
          round_course_place: 'KTH Campus',
          round_campus: 'KTH Campus',
          round_short_name: 'CYPRESS4',
          round_application_code: '60493',
          round_schedule: '<i>No information inserted</i>',
          round_study_pace: 17,
          round_course_term: ['2025', '1'],
          round_periods: 'P3 (2.0 hp), P4 (4.5 hp)',
          round_seats: '',
          round_selection_criteria: '<p></p>',
          round_type: 'Programutbildning',
          round_funding_type: 'ORD',
          round_application_link: '<i>No information inserted</i>',
          round_part_of_programme: '<i>No information inserted</i>',
          round_state: 'APPROVED',
          round_comment: '',
          round_category: 'PU',
        },
      ],
    },
    courseTitleData: {
      course_code: 'SF1624',
      course_title: 'Algebra and Geometry',
      course_other_title: 'Algebra och geometri',
      course_credits: 7.5,
      course_credits_text: 'hp',
    },
    syllabusSemesterList: [
      [20192, ''],
      [20102, 20191],
      [20092, 20101],
      [20082, 20091],
    ],
    language: 'en',
  },
  setBrowserConfig: function setBrowserConfig(config, paths, hostUrl) {
    this.browserConfig = config
    this.paths = paths
    this.hostUrl = hostUrl
  },
  browserConfig: {
    hostUrl: 'http://localhost:3000',
    useSsl: false,
    port: 3000,
    proxyPrefixPath: {
      uri: '/student/kurser/kurs',
    },
    imageStorageUri: 'https://kursinfostoragestage.blob.core.windows.net/kursinfo-image-container/',
    memoStorageUri: 'https://kursinfostoragestage.blob.core.windows.net/memo-blob-container/',
    analysisStorageUri: 'https://kursinfostoragestage.blob.core.windows.net/kursutveckling-blob-container/',
    env: 'dev',
  },
  paths: {
    system: {
      monitor: {
        uri: '/student/kurser/kurs/_monitor',
        method: 'get',
      },
      about: {
        uri: '/student/kurser/kurs/_about',
        method: 'get',
      },
      paths: {
        uri: '/student/kurser/kurs/_paths',
        method: 'get',
      },
      robots: {
        uri: '/robots.txt',
        method: 'get',
      },
      experiment: {
        index: {
          uri: '/student/kurser/kurs/experiment/:courseCode',
          method: 'get',
        },
      },
      index: {
        uri: '/student/kurser/kurs/:courseCode',
        method: 'get',
      },
      home: {
        uri: '/student/kurser/kurs/',
        method: 'get',
      },
    },
    statistics: {
      getData: {
        uri: '/student/kurser/kurs/statistik',
        method: 'get',
      },
    },
    api: {
      statisticsMemo: {
        uri: '/student/kurser/kurs/api/kursinfo/statistics/courseMemo/year/:year',
        method: 'get',
      },
      statisticsAnalysis: {
        uri: '/student/kurser/kurs/api/kursinfo/statistics/courseAnalysis/year/:year',
        method: 'get',
      },
      koppsCourseData: {
        uri: '/student/kurser/kurs/api/kursinfo/getKoppsCourseDataByCourse/:courseCode/:language',
        method: 'get',
      },
    },
    SyllabusPdf: {
      getPdfProxy: {
        uri: '/student/kurser/kurs/kursplan/:course_semester',
        method: 'get',
      },
    },
    ug: {
      rest: {
        api: {
          uri: '/student/kurser/kurs/ug/rest',
          method: 'post',
        },
      },
    },
  },
  hostUrl: 'http://localhost:3000',
}
